####################################################################################################
### create_env_nsets
### Generate multiple sets of environmental variables. Essentially a wrapper around create_env_set.
### For a given set, the first variable is generated using create_env and then subsequent variables
### are generated based on sampling a subset of the 1st variable. Each new variable is generated
### using a random range parameter generated from the rangeFun. Therefore a given set of variables
### are related but with some random variation between them, and each set starts from a random new
### base variable.
###
### 01/2022
### Charlie Marsh (charlie.marsh@mailbox.org)
###
### cellDims  = vector containing variable dimensions (n cell width, n cell height)
### sets      = a vector with the number of variables for each set (generated by create_env_set).
###             Each set is generated from a new randomly generated base environmental variable.
### model     = model for variogram; default = "Sph" (see ?vgm for options)
### psill     = (partial) sill of the variogram model; default = 1.5 (see ?vgm for options)
### vrange    = name of function (in quotes!) to generate random number for the range parameter of
###             the variogram model. E.g. function() exp(runif(1, 1, 6))
### propSamp  = propotion of cells to sample in each submodel (default = 0.5)
### dep1      = multiplied by the psill in submodels (default = 1)
###
### output:
###   a raster stack of multiple environmental variable sets. The name of each raster relates to the
###   number of the variable set, and then the number of the variable within that set.
###
####################################################################################################

create_env_nsets <- function(cellDims = c(100, 100),
                             sets    = c(5, 4, 3, 1),
                             model    = "Sph",
                             psill    = 1.5,
                             dep1     = 1,     # multiplied against psill
                             rangeFun = "vrangeFun",
                             propSamp = 0.25) {
  require(gstat)
  require(sp)
  require(raster)

  allSets <- list()
  for(set in 1:length(sets)) {
    print(paste("set", set))
    envSet <- create_env_set(cellDims = c(100,100),
                             nPerSet  = sets[set],
                             model    = "Sph",
                             psill    = 1,
                             dep1     = 0.01,
                             propSamp = 0.1,
                             rangeFun = "vrangeFun")

    ### rename
    names(envSet) <- paste0("var_", set, ".", 1:sets[set])
    allSets[[set]] <- envSet
  }

  print("stacking")
  allSets <- stack(allSets)
  return(allSets)
}
